### ISSUE TITLE
Platform banner image is blurred?

### ISSUE THREAD

**Issue by suxiaogang** [Fr75s/library#1]
Hi thanks for your nice job making this awesome theme and I really love it !

I install it on my Retroid Pocket 3 Plus and just found that, the platform banner image is blurred and there isn't an option to change the transparency percentage in the setting. Is this designed so or might be a bug ?

![Screenshot_20221201-101220](https://user-images.githubusercontent.com/1567518/204949380-766822c2-c76c-46ee-b006-43bde19c3ef8.png)

**Comment by suxiaogang** [comment]
Also, I want to make some modifications  / or a fork theme to move the [Collections] tab to the first place.
Any guide to this modification?

**Comment by Fr75s** [comment]
This has been fixed in b7e77a1; The option to toggle blur is the 5th option.

As for your modification, in `theme.qml` there is a Row called `bbImages` containing Images representing icons for each collection. Swap the placement of `bbCollect` and `bbHome` found here. Then, you would want to go to the place in theme.qml where each page is defined (where it says Home {...}, All {...}...) and set the focus of Home to `(menu==2)` and the focus of Collections to `(menu == 0)`. This should at least get you started.
