### ISSUE TITLE
First game still wide even when all wide options are disabled

### ISSUE THREAD

**Issue by ghost** [Fr75s/library#11]
Hello!
The first game on "recent games" tab is always wide, even when the option for wide games banner is off. Could we have an option to completely disable wide banners, even on the "recent games" tab?
My images aren't really designed to be wide, so that would make my home page really better looking :)
Thanks in advance for your answer!

**Comment by Fr75s** [comment]
This has been fixed in commit 84db425.

A new option in the interface section of the settings, "Override Wide 1st Recent Game," has been added beneath "Show Playtime" and above "Change Bar Size."

Here's what it looks like with the new option enabled:
![The Main Menu of Library, with the first entry under "Recent Games" having the same aspect ratio as the other entries.](https://github.com/Fr75s/library/assets/98292839/9548c077-da7d-4e2d-a813-13df6872a29b)

Hopefully this works for you.

**Comment by ghost** [comment]
That's awesome, thanks a lot!
